services:
  postgres:
    image: postgres:16
    container_name: first_hw_postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app123
      POSTGRES_DB: petshopdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d petshopdatabase"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  flyway:
    image: flyway/flyway:latest
    container_name: first_hw_flyway
    command: migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/petshopdatabase
      FLYWAY_USER: app
      FLYWAY_PASSWORD: app123
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data: